### ISSUE TITLE
Error occured while writing database

### ISSUE THREAD

**Issue by mallanos** [forlilab/Ringtail#23]
While running the following command to write a database, I'm getting the following error:
The error appeared after a fix introduced to handle cases where no interactions could be found for a ligand.

rt_process_vs.py write --file_path output/5rlh --output_db 5rlh.db --max_poses 5 --summary --receptor_file receptors/pocket1/5rlh_fix.pdbqt --debug | tee out_5rlh.log
Logging level set to debug
Adding results...
{'file': [[]], 'file_path': {'path': [['output/5rlh']], 'pattern': '*.dlg*', 'recursive': False}, 'file_list': [[]]}
Starting 63 file readers
-Scanning directory [output/5rlh] for files (pattern:|*.dlg*|)
2301 files written to database. Writing 30264 files/minute. Elapsed time 5 seconds.Caught error in multiprocessing from Database
Error encountered while handling Database
Traceback (most recent call last):
  File "/gpfs/home/mllanos/Ringtail/ringtail/mpreaderwriter.py", line 281, in run
    self.write_to_storage()
  File "/gpfs/home/mllanos/Ringtail/ringtail/mpreaderwriter.py", line 317, in write_to_storage
    self.storageman.insert_data(
  File "/gpfs/home/mllanos/Ringtail/ringtail/storagemanager.py", line 1563, in insert_data
    self.insert_results(results_array)
  File "/gpfs/home/mllanos/Ringtail/ringtail/storagemanager.py", line 1621, in insert_results
    cur.executemany(sql_insert, results_array)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 33, and there are 32 supplied.

Closing database
Traceback (most recent call last):
  File "/gpfs/home/mllanos/Ringtail/ringtail/mpmanager.py", line 120, in process_files
    self._process_sources()
  File "/gpfs/home/mllanos/Ringtail/ringtail/mpmanager.py", line 156, in _process_sources
    self._add_to_queue(f)
  File "/gpfs/home/mllanos/Ringtail/ringtail/mpmanager.py", line 180, in _add_to_queue
    self._check_for_worker_exceptions()
  File "/gpfs/home/mllanos/Ringtail/ringtail/mpmanager.py", line 193, in _check_for_worker_exceptions
    self._kill_all_workers(error, filename, tb)
  File "/gpfs/home/mllanos/Ringtail/ringtail/mpmanager.py", line 204, in _kill_all_workers
    raise error
ringtail.exceptions.WriteToStorageError: Error occured while writing database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home/mllanos/Ringtail/scripts/rt_process_vs.py", line 51, in <module>
    rt_core.add_results()
  File "/gpfs/home/mllanos/Ringtail/ringtail/ringtailcore.py", line 136, in add_results
    self.results_man.process_results()
  File "/gpfs/home/mllanos/Ringtail/ringtail/resultsmanager.py", line 80, in process_results
    self.parser.process_files()
  File "/gpfs/home/mllanos/Ringtail/ringtail/mpmanager.py", line 123, in process_files
    self._kill_all_workers("file sources", tb)
TypeError: _kill_all_workers() missing 1 required positional argument: 'tb'

ERROR: _kill_all_workers() missing 1 required positional argument: 'tb'

**Comment by althea-hansel** [comment]
Should be fixed by commit 97e910463ed1efbc1c59a7d18f3681a68cf25c76
