### ISSUE TITLE
Question about the information returned in --outfields with n_interact

### ISSUE THREAD

**Issue by xavgit** [forlilab/Ringtail#66]
Hi,
with the results of a vina docking I've constructed a corresponding .db file and then with the command:

$ rt_process_vs read --input_db c1_vina_vina__sf.db  --score_percentile 5.2 --log_file output_log_c1_vina_vina_sf_scpct_5.2percent.txt  --order_results e --outfields Ligand_name,e,rank,le,delta,n_interact --bookmark_name c1VinaVinaSfScorePerctFiveDotTwoPercent 
 
I've analyzed the output log in which there are the following lines:

Result bookmark name: c1VinaVinaSfScorePerctFiveDotTwoPercent
\***************
'DB09074_vina_sf__docked', -10.984, 1, -0.34325, 0.0, 114
'DB18657_vina_sf__docked', -10.9, 1, -0.3027777777777778, 0.0, 129
'DB15637_vina_sf__docked', -10.583, 1, -0.31126470588235294, 0.0, 93
'DB12424_vina_sf__docked', -10.532, 1, -0.2568780487804878, 0.0, 116
'DB12457_vina_sf__docked', -10.392, 1, -0.26646153846153847, 0.0, 116
...................................................................................................................................
It is possible to obtain the list of the n_interact-ing  residues of the receptor?
For the line
'DB09074_vina_sf__docked', -10.984, 1, -0.34325, 0.0, 114
the list of the 114 residues or their involved atoms.

This can be useful to  understand the distribution of the receptor residues interacting 
with one or more molecules.

For one drug , for example , with  --output_all_poses:
$ less output_log_c1_vina_vina_sf_scpct_99.999percent_all_poses.txt | grep  DB09074_vina_sf__docked
'DB09074_vina_sf__docked', -10.984, 1, -0.34325, 0.0, 114
'DB09074_vina_sf__docked', -10.42, 2, -0.325625, 0.5640000000000001, 118
'DB09074_vina_sf__docked', -10.014, 3, -0.3129375, 0.9700000000000006, 106
'DB09074_vina_sf__docked', -9.481, 4, -0.29628125, 1.5030000000000001, 120
'DB09074_vina_sf__docked', -9.275, 5, -0.28984375, 1.7089999999999996, 98
'DB09074_vina_sf__docked', -9.186, 6, -0.2870625, 1.798, 105
'DB09074_vina_sf__docked', -9.111, 7, -0.28471875, 1.8729999999999993, 86
'DB09074_vina_sf__docked', -8.967, 8, -0.28021875, 2.0169999999999995, 84
'DB09074_vina_sf__docked', -8.927, 9, -0.27896875, 2.0570000000000004, 98
'DB09074_vina_sf__docked', -8.915, 10, -0.27859375, 2.069000000000001, 114
'DB09074_vina_sf__docked', -8.831, 11, -0.27596875, 2.1530000000000005, 96
'DB09074_vina_sf__docked', -8.746, 13, -0.2733125, 2.2379999999999995, 105
'DB09074_vina_sf__docked', -8.746, 12, -0.2733125, 2.2379999999999995, 106
'DB09074_vina_sf__docked', -8.731, 14, -0.27284375, 2.253, 102
'DB09074_vina_sf__docked', -8.608, 15, -0.269, 2.3759999999999994, 100
'DB09074_vina_sf__docked', -8.508, 16, -0.265875, 2.476000000000001, 111

Thanks.

Saverio

**Comment by maylinnp** [comment]
I'll look at possibilities for some better API implementation for future release. One method that will work for now, is to use the command line option to export a sqlite query as a csv file. 
Below is an example cmdline prompt including an sqlite formatted query that will select ligand name and residue information for all poses/ligands that passed filtering in the given bookmark. In your case <bookmark_name> would be changed to c1VinaVinaSfScorePerctFiveDotTwoPercent. The output will be saved as "query.csv" (unless you use the API in which case you can set the name of the csv). 

`
rt_process_vs read --input_db c1_vina_vina__sf.db --export_query_csv "SELECT pr.LigName, ii.* FROM (interaction_indices ii JOIN interactions i ON i.interaction_id = ii.interaction_id) int JOIN <bookmark_name> pr ON int.pose_id = pr.pose_id ORDER BY ii.rec_resname" 
`

Let me know how this works for you or if you have any issues with the prompt.

**Comment by xavgit** [comment]
Hi,
it work perfectly.
Following the first lines of the produced csv:
,LigName,interaction_id,interaction_type,rec_chain,rec_resname,rec_resid,rec_atom,rec_atomid
0,DB09074_vina_sf__docked,10,V,,ALA,407,C,3824
1,DB09074_vina_sf__docked,20,V,,ALA,327,CB,3036
2,DB18657_vina_sf__docked,10,V,,ALA,407,C,3824
3,DB18657_vina_sf__docked,20,V,,ALA,327,CB,3036
4,DB15637_vina_sf__docked,10,V,,ALA,407,C,3824
5,DB15637_vina_sf__docked,20,V,,ALA,327,CB,3036
6,DB12424_vina_sf__docked,10,V,,ALA,407,C,3824
7,DB12424_vina_sf__docked,20,V,,ALA,327,CB,3036
8,DB12424_vina_sf__docked,24,V,,ALA,407,N,3820

Only one information lacks: the association between a specific ligand binding pose and its contacts
with the receptor.
With the command:
$ less query.csv | grep  DB09074_vina_sf__docked
0,DB09074_vina_sf__docked,10,V,,ALA,407,C,3824
1,DB09074_vina_sf__docked,20,V,,ALA,327,CB,3036
1590,DB09074_vina_sf__docked,73,H,,ASN,244,1HD2,2247
1591,DB09074_vina_sf__docked,80,V,,ASN,244,ND2,2246
1592,DB09074_vina_sf__docked,83,V,,ASN,244,CG,2244
1593,DB09074_vina_sf__docked,92,H,,ASN,244,2HD2,2248
4322,DB09074_vina_sf__docked,11,V,,ASP,413,CG,3872
4323,DB09074_vina_sf__docked,15,V,,ASP,230,CG,2122
4324,DB09074_vina_sf__docked,43,V,,ASP,413,CB,3871
4325,DB09074_vina_sf__docked,45,V,,ASP,230,CB,2121
4326,DB09074_vina_sf__docked,62,V,,ASP,413,CA,3870
4327,DB09074_vina_sf__docked,93,H,,ASP,413,OD2,3874
6347,DB09074_vina_sf__docked,81,V,,CYS,234,N,2150
6452,DB09074_vina_sf__docked,0,V,,GLN,285,NE2,2608
6453,DB09074_vina_sf__docked,3,V,,GLN,394,CD,3695
6454,DB09074_vina_sf__docked,6,V,,GLN,394,N,3690
6455,DB09074_vina_sf__docked,12,V,,GLN,285,CB,2604
6456,DB09074_vina_sf__docked,22,V,,GLN,394,CG,3694
6457,DB09074_vina_sf__docked,30,V,,GLN,394,CB,3693
6458,DB09074_vina_sf__docked,33,H,,GLN,285,1HE2,2609
6459,DB09074_vina_sf__docked,35,H,,GLN,285,2HE2,2610
11110,DB09074_vina_sf__docked,41,V,,GLU,232,CD,2140
11111,DB09074_vina_sf__docked,84,V,,GLU,232,CA,2137
11112,DB09074_vina_sf__docked,110,H,,GLU,232,OE2,2142
11113,DB09074_vina_sf__docked,111,V,,GLU,232,N,2135
11114,DB09074_vina_sf__docked,113,V,,GLU,232,C,2143
12990,DB09074_vina_sf__docked,71,V,,GLY,233,CA,2147
12991,DB09074_vina_sf__docked,76,V,,GLY,233,N,2145
12992,DB09074_vina_sf__docked,78,V,,GLY,233,C,2148
14509,DB09074_vina_sf__docked,5,V,,HID,408,CD2,3835
14510,DB09074_vina_sf__docked,17,V,,HID,408,CG,3830
14511,DB09074_vina_sf__docked,32,V,,HID,408,CA,3828
14512,DB09074_vina_sf__docked,37,V,,HID,408,N,3826
14513,DB09074_vina_sf__docked,105,V,,HID,408,CB,3829
16646,DB09074_vina_sf__docked,4,V,,LEU,393,CG,3685
16647,DB09074_vina_sf__docked,7,V,,LEU,393,CD2,3687
16648,DB09074_vina_sf__docked,29,V,,LEU,393,CB,3684
18732,DB09074_vina_sf__docked,21,V,,MET,416,CE,3898
19229,DB09074_vina_sf__docked,2,V,,PHE,286,CZ,2620
19230,DB09074_vina_sf__docked,40,V,,PHE,286,CE2,2621
19231,DB09074_vina_sf__docked,59,V,,PHE,286,CE1,2619
19232,DB09074_vina_sf__docked,66,V,,PHE,330,CB,3059
19233,DB09074_vina_sf__docked,67,V,,PHE,330,CE2,3064
19234,DB09074_vina_sf__docked,68,V,,PHE,330,CG,3060
19235,DB09074_vina_sf__docked,69,V,,PHE,330,CD2,3065
19236,DB09074_vina_sf__docked,74,V,,PHE,330,CZ,3063
19237,DB09074_vina_sf__docked,89,V,,PHE,286,CD2,2622
23892,DB09074_vina_sf__docked,70,V,,PRO,281,CG,2575
24936,DB09074_vina_sf__docked,34,V,,TRP,326,CD1,3022
24937,DB09074_vina_sf__docked,57,V,,TRP,326,C,3031
26610,DB09074_vina_sf__docked,75,V,,VAL,231,C,2133
26611,DB09074_vina_sf__docked,104,H,,VAL,409,H,3839
26612,DB09074_vina_sf__docked,107,V,,VAL,409,N,3838
and 
$ less query.csv | grep  DB09074_vina_sf__docked | wc -l 
53

I infer that there are 53 contacts for 16 poses.
It is possible ( if it doesn't require much time ) to have the lacking association 
between a ligand binding pose and its contacts with the receptor?
It is possible to know the meaning of the codes of the field interaction_type?
It can be an interesting information.

Thanks.

Saverio

**Comment by xavgit** [comment]
Hi,
one more question.
I have noticed that --score_percentile accept as argument 99.999 but not 100.00.
In the last case it returns with the following:
$ rt_process_vs read --input_db c1_vina_vina__sf.db  --score_percentile 100.00 --log_file output_log_c1_vina_vina_sf_scpct_100.00percent_all_poses.txt  --order_results e --outfields Ligand_name,e,rank,le,delta,n_interact --bookmark_name c1VinaVinaSfScorePerctOneZeroZeroDotZeroZeroPercentAllPoses --output_all_poses 
/home/xxxx/.local/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
ERROR - storagemanager.py:114 - local variable 'cutoff' referenced before assignment
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/ringtailcore.py", line 1386, in filter
    filtered_results = self.storageman.filter_results(
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/storagemanager.py", line 226, in filter_results
    filter_results_str, view_query = self._generate_result_filtering_query(
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/storagemanager.py", line 2542, in _generate_result_filtering_query
    processed_filters = self._process_filters_for_query(filters_dict)
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/storagemanager.py", line 2429, in _process_filters_for_query
    cutoff = self._calc_percentile_cutoff(
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/storagemanager.py", line 2374, in _calc_percentile_cutoff
    self.logger.debug(f"{column} percentile cutoff is {cutoff}")
UnboundLocalError: local variable 'cutoff' referenced before assignment
CRITICAL - rt_process_vs.py:102 - ERROR: local variable 'cutoff' referenced before assignment
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/cli/rt_process_vs.py", line 55, in main
    rtcore.filter(
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/ringtailcore.py", line 1383, in filter
    with self.storageman:
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/storagemanager.py", line 115, in __exit__
    raise exc_value from None
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/ringtailcore.py", line 1386, in filter
    filtered_results = self.storageman.filter_results(
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/storagemanager.py", line 226, in filter_results
    filter_results_str, view_query = self._generate_result_filtering_query(
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/storagemanager.py", line 2542, in _generate_result_filtering_query
    processed_filters = self._process_filters_for_query(filters_dict)
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/storagemanager.py", line 2429, in _process_filters_for_query
    cutoff = self._calc_percentile_cutoff(
  File "/home/xxxx/.local/lib/python3.10/site-packages/ringtail/storagemanager.py", line 2374, in _calc_percentile_cutoff
    self.logger.debug(f"{column} percentile cutoff is {cutoff}")

The meaning of 100.00 is all the values.
Why this errror?

Thanks. 

Saverio

**Comment by maylinnp** [comment]
The reason for the error is that filtering 100 % of the value would not perform any filtering, so Ringtail has a cutoff as score_percentile < 100. 

The error message does not make this super clear, fortunately error handling and messages are being worked on for a future release.

**Comment by maylinnp** [comment]
@xavgit could you help me understand what you mean by your question "It is possible ( if it doesn't require much time ) to have the lacking association between a ligand binding pose and its contacts with the receptor?". It's not immediately clear to me what "association" and "contacts" mean. 

The interaction_type field tells you whether it is a van der Waals (V) or hydrogen bond (H) interaction.

**Comment by xavgit** [comment]
Hi,
yes, I was not so clear.
For the score_percentile I should like to use 100.0 so to take into account all the scoring 
values without using the accepted approximation 99.999.

For the interaction_type there are many codes in the second column:
,LigName,interaction_id,interaction_type,rec_chain,rec_resname,rec_resid,rec_atom,rec_atomid
0,DB04362,53,V,,ALA,327,CB,3034
1,DB02254,40,V,,ALA,407,C,3817
2,DB02254,50,H,,ALA,407,N,3820
3,DB02254,71,V,,ALA,407,CA,3819
4,DB02254,126,H,,ALA,407,O,3818
5,DB02809,40,V,,ALA,407,C,3817

What is the meaning of 53,40,50,71 and so on?

For the "association" and "contacts" I mean to obtain 
pose 1  <--> contacts of pose 1
.........................................................
pose N <--> contacts pose N

If you read the above
 less output_log_c1_vina_vina_sf_scpct_99.999percent_all_poses.txt | grep DB09074_vina_sf__docked
then you know that there are 16 poses
and from
less query.csv | grep DB09074_vina_sf__docked | wc -l
53
we know that the the union of all the interactions of all pose of DB09074  is 53.
Right?

In another case collecting the data for  grep DB18715
I obtain 427 rows
$ less query_99.999.csv | grep DB18715
141138,DB18715_vina_sf__docked,101,H,,ALA,407,H,3821
141139,DB18715_vina_sf__docked,10,V,,ALA,407,C,3824
141140,DB18715_vina_sf__docked,24,V,,ALA,407,N,3820
141141,DB18715_vina_sf__docked,42,V,,ALA,407,CA,3822
141142,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141143,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141144,DB18715_vina_sf__docked,64,V,,ALA,327,CA,3035
141145,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141146,DB18715_vina_sf__docked,90,V,,ALA,327,C,3037
141147,DB18715_vina_sf__docked,10,V,,ALA,407,C,3824
141148,DB18715_vina_sf__docked,64,V,,ALA,327,CA,3035
141149,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141150,DB18715_vina_sf__docked,98,V,,ALA,327,N,3033
141151,DB18715_vina_sf__docked,154,V,,ALA,410,N,3846
141152,DB18715_vina_sf__docked,10,V,,ALA,407,C,3824
141153,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141154,DB18715_vina_sf__docked,24,V,,ALA,407,N,3820
141155,DB18715_vina_sf__docked,98,V,,ALA,327,N,3033
141156,DB18715_vina_sf__docked,42,V,,ALA,407,CA,3822
141157,DB18715_vina_sf__docked,148,H,,ALA,327,O,3038
141158,DB18715_vina_sf__docked,64,V,,ALA,327,CA,3035
141159,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141160,DB18715_vina_sf__docked,90,V,,ALA,327,C,3037
141161,DB18715_vina_sf__docked,98,V,,ALA,327,N,3033
141162,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141163,DB18715_vina_sf__docked,90,V,,ALA,327,C,3037
141164,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141165,DB18715_vina_sf__docked,10,V,,ALA,407,C,3824
141166,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141167,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141168,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141169,DB18715_vina_sf__docked,90,V,,ALA,327,C,3037
141170,DB18715_vina_sf__docked,64,V,,ALA,327,CA,3035
141171,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141172,DB18715_vina_sf__docked,90,V,,ALA,327,C,3037
141173,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
141174,DB18715_vina_sf__docked,90,V,,ALA,327,C,3037
141175,DB18715_vina_sf__docked,10,V,,ALA,407,C,3824
141176,DB18715_vina_sf__docked,20,V,,ALA,327,CB,3036
545687,DB18715_vina_sf__docked,92,H,,ASN,244,2HD2,2248
545688,DB18715_vina_sf__docked,73,H,,ASN,244,1HD2,2247
545689,DB18715_vina_sf__docked,9,V,,ASN,392,CB,3673
545690,DB18715_vina_sf__docked,102,H,,ASN,406,H,3810
545691,DB18715_vina_sf__docked,16,V,,ASN,406,CA,3811
.........................................................................................................

In the first lines , for the ALA 327 residue , some of its atoms are repeated
many times.

257580,DB18716_vina_sf__docked,20,V,,ALA,327,CB,3036
257581,DB18716_vina_sf__docked,20,V,,ALA,327,CB,3036
257583,DB18716_vina_sf__docked,20,V,,ALA,327,CB,3036
257585,DB18716_vina_sf__docked,20,V,,ALA,327,CB,3036
257586,DB18716_vina_sf__docked,20,V,,ALA,327,CB,3036
257587,DB18716_vina_sf__docked,20,V,,ALA,327,CB,3036
257588,DB18716_vina_sf__docked,20,V,,ALA,327,CB,3036
257589,DB18716_vina_sf__docked,20,V,,ALA,327,CB,3036

If , for example the CB is repeated 8 times , it means that eight different 
poses of the same drug have an interaction of type vdw with the CB of 
ALA 327 of the receptor?
RIght?

Thanks.

Saverio

**Comment by maylinnp** [comment]
Regarding score percentile: if you want to -not- filter using score_percentile, you can simply omit that command line keyword. 

The extra number in the output file is the `interaction_id` which is the index of the column in the `Interactions` table. The suggested query just grabs all columns from the `Interactions` table which includes the index. 

Regarding the interaction question, yes that is what it would mean. It is possible to alter the query to include pose_id as well, if you wish to dig deeper. 

`rt_process_vs read --input_db c1_vina_vina__sf.db --export_query_csv "SELECT pr.LigName, pr.pose_id, ii.* FROM (interaction_indices ii JOIN interactions i ON i.interaction_id = ii.interaction_id) int JOIN <bookmark_name> pr ON int.pose_id = pr.pose_id ORDER BY ii.rec_resname" `

**Comment by xavgit** [comment]
Hi,
thanks for your very useful explanations.

Saverio
